---
title: "Homework 9"
author: "Maddie Winer"
date: "2025-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
x<-read.csv("Raw_data.csv")

#linear regression
regression <- ggplot(x, aes(x = abundance, y = richness)) +
  geom_point() +  
  geom_smooth(method = "lm", se = FALSE, color = "blue") +  
  labs(title = "Linear Regression: Species Richness vs Abundance",
       x = "Abundance",
       y = "Species Richness")
regression

# Generate histograms for both Abundance and Species Richness (S) and store the plots
abundance_histogram <- ggplot(x, aes(x = abundance)) +
  geom_histogram(fill = "goldenrod", color = "black",) +
  labs(title = "Histogram of Abundance", x = "Abundance", y = "Frequency") +
  theme_minimal()
abundance_histogram

richness_histogram <- ggplot(x, aes(x = richness)) +
  geom_histogram(fill = "coral", color = "black", ) + 
  labs(title = "Histogram of Species Richness", x = "Species Richness", y = "Frequency") +
  theme_minimal()
richness_histogram

# Regression Summary Statistics
# store regression summary stats into a new dataframe 
model <- lm(richness~abundance, data=x)
regression_summary <- summary(model)
regression_summary<- as.data.frame(regression_summary$coefficients)
colnames(regression_summary) <- c("Estimate", "StdError", "tValue", "pValue")
regression_summary

```
